### ISSUE TITLE
AWESim_SOSS .git is 1GB

### ISSUE THREAD

**Issue by exowanderer** [spacetelescope/awesimsoss#11]
The `.git` directory for AWESim_SOSS is 1GB by itself; but the entire code is only ~400MB.  

Can we prune the `.git` base? 

See [How can I clean my .git folder? Cleaned up my project directory, but .git is still massive
](https://stackoverflow.com/questions/5277467/how-can-i-clean-my-git-folder-cleaned-up-my-project-directory-but-git-is-sti)

**Comment by hover2pi** [comment]
Fixed!
