### ISSUE TITLE
python setup.py install broken

### ISSUE THREAD

**Issue by exowanderer** [spacetelescope/awesimsoss#16]
Behaviour:
-----------
The installation process finishes successfully
```bash
pip install git+https://github.com/spacetelescope/awesimsoss
```
results in: `Successfully built awesimsoss`

The failure occurs with `python -c "import awesimsoss"`, which results with 
`ModuleNotFoundError: No module named 'awesimsoss'`.

[Note: I also cloned the github repo and ran `python setup.py install`]

There exists a directory in my site-packages `$HOME/anaconda3/lib/python3.6/site-packages/awesimsoss-0.1-py3.6.egg/`. But the contents of that directory are only the `EGG-INFO` directory, and not `awesimsoss` directory; the latter is necessary for python to `import awesimsoss`.

It's likely that the `setup.py` file does not properly include the necessary features to create the full egg for installation.

**Comment by hover2pi** [comment]
Fixed in #14
