### ISSUE TITLE
Python kernel dies for simulations with more than 200 groups

### ISSUE THREAD

**Issue by radicamc** [spacetelescope/awesimsoss#53]
This may be similar to one mentioned by @talensgj and @njcuk9999 in issue #32. I am able to run the simple example in the readme file. I am working on Mac OS X with 16GB of RAM, but have swap memory available whereas their linux architectures does not.
However, if I wish to run a realistic transit simulation, my python kernel will die for anything greater than 200 total groups (corresponding to ~17 minutes of observation time).

**Comment by hover2pi** [comment]
@radicamc This is a top priority and I'm working on it now!

**Comment by hover2pi** [comment]
Debugging notes for posterity:

For 2 groups and 2 integrations, Activity Monitor says initializing a `TSO` object takes up about 600MB of memory, mostly from preloading the (2048, 256, 76) PSF cube for each order.

Running `simulate` bumps that up to 2GB while the simulation is running and then drops back down to ~675MB, with the added memory going to the results stored in the attributes 'tso', 'tso_ideal', 'tso_order1_ideal`, `tso_order2_ideal`. Perhaps I should just store the realistic simulation and let the user opt into the the noiseless simulations or dump them into a file and clear the memory. This will be better but this is not the real issue. The memory usage during the `simulate` method is what needs to be addressed.

For 100 integrations and 3 groups, the memory usage jumps up to about 120GB in `python` and about 10GB in `kernel_task` before a `Killed: 9` is issued in Terminal.

<img width="559" alt="Screen Shot 2020-05-11 at 9 34 12 PM" src="https://user-images.githubusercontent.com/34687/81628720-6cbc1400-93cf-11ea-984b-d0549675523a.png">

**Comment by hover2pi** [comment]
Fixed in #73
