### ISSUE TITLE
Near-saturated pixels seem to be missing flux

### ISSUE THREAD

**Issue by hover2pi** [spacetelescope/awesimsoss#55]
Pixels that are saturated or near-saturated seem to be missing flux across the entire trace.

<img width="860" alt="Screen Shot 2020-01-08 at 2 14 43 PM" src="https://user-images.githubusercontent.com/34687/72008961-e6c26d80-3222-11ea-866e-73701ff08617.png">

**Comment by hover2pi** [comment]
Seems to be in the generate noise portion of the code since generating a simulation with a really high flux density and inspecting the trace with the noise off looks fine.

**Comment by hover2pi** [comment]
@nespinoza You and @KevinVolkSTScI had a fix for this, right? Have you made that PR yet or can I make the change? I just pulled from master and the issue still seems to be there. Thanks!

**Comment by nespinoza** [comment]
Hey-hey @hover2pi! Yes, my fault --- going to submit a PR now to fix this. Give me some minutes :-).

**Comment by hover2pi** [comment]
Thanks @nespinoza ! Fixed in #65 .
