### ISSUE TITLE
header compatibility with stage 1 pipeline

### ISSUE THREAD

**Issue by talensgj** [spacetelescope/awesimsoss#58]
I ran a simple awesimsoss image through the stage 1 pipeline, but had to make 3 changes to the headers to make this work.

DATE-OBS is currently given as MM/DD/YYYY but the pipeline expects DD/MM/YYYY.
NRSTSTRT the number of resets at the start of the exposure, was missing.
NRESETS the number of resets between integrations, was missing.

**Comment by radicamc** [comment]
This should be fixed in pull request #56.

**Comment by hover2pi** [comment]
The description the FITS file stores in the header for the `OBS-DATE` card reads "[yyyy-mm-dd] UTC date at start of exposure" so should it be `%Y-%m-%d`?

**Comment by radicamc** [comment]
I think so. The pipeline appears to accept both ```%Y-%m-%d``` and ```%d/%m/%Y``` formats for ```OBS-DATE``` in any case.

**Comment by radicamc** [comment]
This is now fixed in pull request #56.

**Comment by hover2pi** [comment]
Fixed in #56.
