### ISSUE TITLE
Missing dependencies in README

### ISSUE THREAD

**Issue by nespinoza** [spacetelescope/awesimsoss#59]
Hi Joe!

 I was trying to use `awesimsoss` but found out the latest version depends on two other packages in order to be installed:

- `hotsoss` (https://github.com/hover2pi/hotsoss).
- `webbpsf` (https://github.com/spacetelescope/webbpsf; see my other issue [here](https://github.com/spacetelescope/awesimsoss/issues/60)).

I pressume these should just be added to the `README.md` file, but was wondering if your plan was making it an official dependency via the `setup.py` --- that's why I didn't push a simple change in the `README.md` file. 

Thanks!
Néstor

**Comment by hover2pi** [comment]
Yup, I'll add it to the dependencies on the next PR. Thanks for the note!

**Comment by hover2pi** [comment]
Added to the `environment.yml` and `requirements_dev.txt` files.
