### ISSUE TITLE
Extremely large fluxes when `t0` (beginning of exposure ) is different from zero

### ISSUE THREAD

**Issue by nespinoza** [spacetelescope/awesimsoss#74]
When using a `t0` different from the default value (`t0 = 0`), `awesimsoss` returns very large values for the fluxes making the frames unusable. For example, a call like the following gives rise to these faulty frames whenever `t0 != 0`:

`tsoframes = ModelTSO(ngrps=ngroups, nints=nintegrations, teff = teff, logg = logg, feh = feh, jmag = jmag, stellar_model = 'ATLAS', t0 = start_time)`

We discussed this internally with @hover2pi, and after much debugging on my side found out this was due to some missing time unit conversions internal to `awesimsoss`. Will be submitting a PR fixing this and other details.

**Comment by hover2pi** [comment]
I restructured the time handling a bunch and address this in #73 . Indeed if `t0` was not 0, the generated time axis is a big number (like JD) that is multiplied with the flux. This line should be the cumulative frame_time in seconds, not the elapsed datetime of the frame.

**Comment by hover2pi** [comment]
This should be fixed in #73 but I'll wait for confirmation until I close this issue.

**Comment by nespinoza** [comment]
Indeed it's fixed! Closing this. Thanks for this @hover2pi!
