### ISSUE TITLE
DATE-OBS and TIME-OBS are not changed according to input t0

### ISSUE THREAD

**Issue by nespinoza** [spacetelescope/awesimsoss#75]
As explained in the title of this issue if, e.g., `t0` (start of observation) is given as an input, the `DATE-OBS` and `TIME-OBS` header values on the simulated data are not changed accordingly. This might be important when simulating data of actual predicted exoplanet transits in order to, e.g., simulate combinations of those datasets with previous (real or simulated) datasets in order to study ephemerides refinement, for instance, and/or the impact on the knowledge of the ephemerides of the system for JWST observations.

**Comment by hover2pi** [comment]
Yeah, I realize I was making `t0` the transit midpoint and also the start time of the observation when these should be different and would never be the case for a real observation. I'll work a fix into #73 . Thanks!

**Comment by hover2pi** [comment]
Fixed in #73
