### ISSUE TITLE
awesimsoss time-stamps give the end of the frame-reads and not the middle

### ISSUE THREAD

**Issue by nespinoza** [spacetelescope/awesimsoss#76]
The time stamps returned by `awesimsoss` are the ones at the end of each frame-read. However, the code should return time-stamps which are at the _middle_ of each frame-read (in theory it should be the time weighted by the flux during a frame-read, but this is not possible to measure).

The middle time-stamps are, I believe, the most representative time for a given frame-read. The easiest way to see this is in the limiting case in which you only have two out-of-transit baseline points and one point taken exactly in-transit. Imagine a transit lasts a frame-time; then, I believe it makes sense for the in-transit point to have the middle of the time spent reading the data and not the time stamp at the end of the frame-time in order for that dataset to make sense. 

This is also important for users that want to sample "real" transit lightcurves accounting for, e.g., the finite frame-read times which would smear out the transit lightcurves at the end. It is assumed in these supersampling schemes (see, e.g., https://arxiv.org/abs/1004.3741) that the time-stamps are in the middle of the read. `batman` also assumes the same to perform supersampling (https://www.cfa.harvard.edu/~lkreidberg/batman/tutorial.html#supersampling).

**Comment by hover2pi** [comment]
Fixed in #73
