### ISSUE TITLE
Missing `EFFEXPTM` keyword in headers

### ISSUE THREAD

**Issue by nespinoza** [spacetelescope/awesimsoss#87]
Hi @hover2pi!

Currently, `awesimsoss` simulations crash in the TSO3 `outlier_detection` step because the `EFFEXPTM` header keyword (effective exposure duration) is not populated (this defines the exposure time for the pipeline to read: https://github.com/spacetelescope/jwst/blob/04dad52af950a652becc79a6d8e3dcb44d255253/jwst/datamodels/schemas/core.schema.yaml#L793).  Currently, the similar `DURATION` keyword is included --- but from a quick read to the Keyword Dictionary (https://mast.stsci.edu/portal/Mashup/Clients/jwkeywords/index.html), it seems that one counts the entire real duration (including resets, dead time, etc.) --- whereas `EFFEXPTM` is just the photon-counting duration of the exposure.

N.

**Comment by hover2pi** [comment]
Thanks @nespinoza ! Fixed in #111 when I updated a bunch of `TSO` properties to reflect the `datamode.xml` PRD file.
